/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef communicate_CONSTANTS_H
#define communicate_CONSTANTS_H

#include "communicate_types.h"

namespace comm {

class communicateConstants {
 public:
  communicateConstants();

};

extern const communicateConstants g_communicate_constants;

} // namespace

#endif
