/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MasterService_H
#define MasterService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "communicate_types.h"

namespace comm {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MasterServiceIf {
 public:
  virtual ~MasterServiceIf() {}
  virtual void getChunkServer(MetaResponse& _return, const MetaRequest& request) = 0;
};

class MasterServiceIfFactory {
 public:
  typedef MasterServiceIf Handler;

  virtual ~MasterServiceIfFactory() {}

  virtual MasterServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MasterServiceIf* /* handler */) = 0;
};

class MasterServiceIfSingletonFactory : virtual public MasterServiceIfFactory {
 public:
  MasterServiceIfSingletonFactory(const ::std::shared_ptr<MasterServiceIf>& iface) : iface_(iface) {}
  virtual ~MasterServiceIfSingletonFactory() {}

  virtual MasterServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MasterServiceIf* /* handler */) {}

 protected:
  ::std::shared_ptr<MasterServiceIf> iface_;
};

class MasterServiceNull : virtual public MasterServiceIf {
 public:
  virtual ~MasterServiceNull() {}
  void getChunkServer(MetaResponse& /* _return */, const MetaRequest& /* request */) {
    return;
  }
};

typedef struct _MasterService_getChunkServer_args__isset {
  _MasterService_getChunkServer_args__isset() : request(false) {}
  bool request :1;
} _MasterService_getChunkServer_args__isset;

class MasterService_getChunkServer_args {
 public:

  MasterService_getChunkServer_args(const MasterService_getChunkServer_args&);
  MasterService_getChunkServer_args& operator=(const MasterService_getChunkServer_args&);
  MasterService_getChunkServer_args() {
  }

  virtual ~MasterService_getChunkServer_args() noexcept;
  MetaRequest request;

  _MasterService_getChunkServer_args__isset __isset;

  void __set_request(const MetaRequest& val);

  bool operator == (const MasterService_getChunkServer_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const MasterService_getChunkServer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterService_getChunkServer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MasterService_getChunkServer_pargs {
 public:


  virtual ~MasterService_getChunkServer_pargs() noexcept;
  const MetaRequest* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterService_getChunkServer_result__isset {
  _MasterService_getChunkServer_result__isset() : success(false) {}
  bool success :1;
} _MasterService_getChunkServer_result__isset;

class MasterService_getChunkServer_result {
 public:

  MasterService_getChunkServer_result(const MasterService_getChunkServer_result&);
  MasterService_getChunkServer_result& operator=(const MasterService_getChunkServer_result&);
  MasterService_getChunkServer_result() {
  }

  virtual ~MasterService_getChunkServer_result() noexcept;
  MetaResponse success;

  _MasterService_getChunkServer_result__isset __isset;

  void __set_success(const MetaResponse& val);

  bool operator == (const MasterService_getChunkServer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MasterService_getChunkServer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterService_getChunkServer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterService_getChunkServer_presult__isset {
  _MasterService_getChunkServer_presult__isset() : success(false) {}
  bool success :1;
} _MasterService_getChunkServer_presult__isset;

class MasterService_getChunkServer_presult {
 public:


  virtual ~MasterService_getChunkServer_presult() noexcept;
  MetaResponse* success;

  _MasterService_getChunkServer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MasterServiceClient : virtual public MasterServiceIf {
 public:
  MasterServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MasterServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getChunkServer(MetaResponse& _return, const MetaRequest& request);
  void send_getChunkServer(const MetaRequest& request);
  void recv_getChunkServer(MetaResponse& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MasterServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<MasterServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MasterServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getChunkServer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MasterServiceProcessor(::std::shared_ptr<MasterServiceIf> iface) :
    iface_(iface) {
    processMap_["getChunkServer"] = &MasterServiceProcessor::process_getChunkServer;
  }

  virtual ~MasterServiceProcessor() {}
};

class MasterServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MasterServiceProcessorFactory(const ::std::shared_ptr< MasterServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< MasterServiceIfFactory > handlerFactory_;
};

class MasterServiceMultiface : virtual public MasterServiceIf {
 public:
  MasterServiceMultiface(std::vector<std::shared_ptr<MasterServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MasterServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<MasterServiceIf> > ifaces_;
  MasterServiceMultiface() {}
  void add(::std::shared_ptr<MasterServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getChunkServer(MetaResponse& _return, const MetaRequest& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getChunkServer(_return, request);
    }
    ifaces_[i]->getChunkServer(_return, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MasterServiceConcurrentClient : virtual public MasterServiceIf {
 public:
  MasterServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  MasterServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getChunkServer(MetaResponse& _return, const MetaRequest& request);
  int32_t send_getChunkServer(const MetaRequest& request);
  void recv_getChunkServer(MetaResponse& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
