/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "communicate_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace comm {

int _kResponseCodeValues[] = {
  ResponseCode::SUCCESS,
  ResponseCode::NEED_D0,
  ResponseCode::ERROR
};
const char* _kResponseCodeNames[] = {
  "SUCCESS",
  "NEED_D0",
  "ERROR"
};
const std::map<int, const char*> _ResponseCode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kResponseCodeValues, _kResponseCodeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const ResponseCode::type& val) {
  std::map<int, const char*>::const_iterator it = _ResponseCode_VALUES_TO_NAMES.find(val);
  if (it != _ResponseCode_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ResponseCode::type& val) {
  std::map<int, const char*>::const_iterator it = _ResponseCode_VALUES_TO_NAMES.find(val);
  if (it != _ResponseCode_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kDataTypeValues[] = {
  DataType::D0,
  DataType::DR,
  DataType::P0,
  DataType::PR
};
const char* _kDataTypeNames[] = {
  "D0",
  "DR",
  "P0",
  "PR"
};
const std::map<int, const char*> _DataType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kDataTypeValues, _kDataTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const DataType::type& val) {
  std::map<int, const char*>::const_iterator it = _DataType_VALUES_TO_NAMES.find(val);
  if (it != _DataType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const DataType::type& val) {
  std::map<int, const char*>::const_iterator it = _DataType_VALUES_TO_NAMES.find(val);
  if (it != _DataType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


ChunkInfo::~ChunkInfo() noexcept {
}


void ChunkInfo::__set_file_id(const int16_t val) {
  this->file_id = val;
}

void ChunkInfo::__set_user_id(const int16_t val) {
  this->user_id = val;
}

void ChunkInfo::__set_segment_id(const int16_t val) {
  this->segment_id = val;
}

void ChunkInfo::__set_chunk_id(const int16_t val) {
  this->chunk_id = val;
}

void ChunkInfo::__set_offset(const int64_t val) {
  this->offset = val;
}

void ChunkInfo::__set_length(const int64_t val) {
  this->length = val;
}
std::ostream& operator<<(std::ostream& out, const ChunkInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ChunkInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_file_id = false;
  bool isset_user_id = false;
  bool isset_segment_id = false;
  bool isset_chunk_id = false;
  bool isset_offset = false;
  bool isset_length = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->file_id);
          isset_file_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->user_id);
          isset_user_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->segment_id);
          isset_segment_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->chunk_id);
          isset_chunk_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->offset);
          isset_offset = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->length);
          isset_length = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_file_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_user_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_segment_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_chunk_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_offset)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_length)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t ChunkInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ChunkInfo");

  xfer += oprot->writeFieldBegin("file_id", ::apache::thrift::protocol::T_I16, 1);
  xfer += oprot->writeI16(this->file_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("user_id", ::apache::thrift::protocol::T_I16, 2);
  xfer += oprot->writeI16(this->user_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("segment_id", ::apache::thrift::protocol::T_I16, 3);
  xfer += oprot->writeI16(this->segment_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("chunk_id", ::apache::thrift::protocol::T_I16, 4);
  xfer += oprot->writeI16(this->chunk_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("offset", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->offset);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("length", ::apache::thrift::protocol::T_I64, 6);
  xfer += oprot->writeI64(this->length);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ChunkInfo &a, ChunkInfo &b) {
  using ::std::swap;
  swap(a.file_id, b.file_id);
  swap(a.user_id, b.user_id);
  swap(a.segment_id, b.segment_id);
  swap(a.chunk_id, b.chunk_id);
  swap(a.offset, b.offset);
  swap(a.length, b.length);
}

ChunkInfo::ChunkInfo(const ChunkInfo& other0) {
  file_id = other0.file_id;
  user_id = other0.user_id;
  segment_id = other0.segment_id;
  chunk_id = other0.chunk_id;
  offset = other0.offset;
  length = other0.length;
}
ChunkInfo& ChunkInfo::operator=(const ChunkInfo& other1) {
  file_id = other1.file_id;
  user_id = other1.user_id;
  segment_id = other1.segment_id;
  chunk_id = other1.chunk_id;
  offset = other1.offset;
  length = other1.length;
  return *this;
}
void ChunkInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ChunkInfo(";
  out << "file_id=" << to_string(file_id);
  out << ", " << "user_id=" << to_string(user_id);
  out << ", " << "segment_id=" << to_string(segment_id);
  out << ", " << "chunk_id=" << to_string(chunk_id);
  out << ", " << "offset=" << to_string(offset);
  out << ", " << "length=" << to_string(length);
  out << ")";
}


Request::~Request() noexcept {
}


void Request::__set_from_id(const int16_t val) {
  this->from_id = val;
}

void Request::__set_to_id(const int16_t val) {
  this->to_id = val;
}

void Request::__set_scheme(const std::string& val) {
  this->scheme = val;
}

void Request::__set_data(const std::vector<int8_t> & val) {
  this->data = val;
}

void Request::__set_length(const int64_t val) {
  this->length = val;
}

void Request::__set_offset(const int64_t val) {
  this->offset = val;
}

void Request::__set_type(const DataType::type val) {
  this->type = val;
}

void Request::__set_partId(const int32_t val) {
  this->partId = val;
}
std::ostream& operator<<(std::ostream& out, const Request& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t Request::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_from_id = false;
  bool isset_to_id = false;
  bool isset_scheme = false;
  bool isset_data = false;
  bool isset_length = false;
  bool isset_offset = false;
  bool isset_type = false;
  bool isset_partId = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->from_id);
          isset_from_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->to_id);
          isset_to_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->scheme);
          isset_scheme = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->data.clear();
            uint32_t _size2;
            ::apache::thrift::protocol::TType _etype5;
            xfer += iprot->readListBegin(_etype5, _size2);
            this->data.resize(_size2);
            uint32_t _i6;
            for (_i6 = 0; _i6 < _size2; ++_i6)
            {
              xfer += iprot->readByte(this->data[_i6]);
            }
            xfer += iprot->readListEnd();
          }
          isset_data = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->length);
          isset_length = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->offset);
          isset_offset = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast7;
          xfer += iprot->readI32(ecast7);
          this->type = (DataType::type)ecast7;
          isset_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->partId);
          isset_partId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_from_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_to_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_scheme)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_data)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_length)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_offset)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_partId)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t Request::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Request");

  xfer += oprot->writeFieldBegin("from_id", ::apache::thrift::protocol::T_I16, 1);
  xfer += oprot->writeI16(this->from_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("to_id", ::apache::thrift::protocol::T_I16, 2);
  xfer += oprot->writeI16(this->to_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("scheme", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->scheme);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("data", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_BYTE, static_cast<uint32_t>(this->data.size()));
    std::vector<int8_t> ::const_iterator _iter8;
    for (_iter8 = this->data.begin(); _iter8 != this->data.end(); ++_iter8)
    {
      xfer += oprot->writeByte((*_iter8));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("length", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->length);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("offset", ::apache::thrift::protocol::T_I64, 6);
  xfer += oprot->writeI64(this->offset);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_I32, 7);
  xfer += oprot->writeI32((int32_t)this->type);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("partId", ::apache::thrift::protocol::T_I32, 8);
  xfer += oprot->writeI32(this->partId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Request &a, Request &b) {
  using ::std::swap;
  swap(a.from_id, b.from_id);
  swap(a.to_id, b.to_id);
  swap(a.scheme, b.scheme);
  swap(a.data, b.data);
  swap(a.length, b.length);
  swap(a.offset, b.offset);
  swap(a.type, b.type);
  swap(a.partId, b.partId);
}

Request::Request(const Request& other9) {
  from_id = other9.from_id;
  to_id = other9.to_id;
  scheme = other9.scheme;
  data = other9.data;
  length = other9.length;
  offset = other9.offset;
  type = other9.type;
  partId = other9.partId;
}
Request& Request::operator=(const Request& other10) {
  from_id = other10.from_id;
  to_id = other10.to_id;
  scheme = other10.scheme;
  data = other10.data;
  length = other10.length;
  offset = other10.offset;
  type = other10.type;
  partId = other10.partId;
  return *this;
}
void Request::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Request(";
  out << "from_id=" << to_string(from_id);
  out << ", " << "to_id=" << to_string(to_id);
  out << ", " << "scheme=" << to_string(scheme);
  out << ", " << "data=" << to_string(data);
  out << ", " << "length=" << to_string(length);
  out << ", " << "offset=" << to_string(offset);
  out << ", " << "type=" << to_string(type);
  out << ", " << "partId=" << to_string(partId);
  out << ")";
}


MetaRequest::~MetaRequest() noexcept {
}


void MetaRequest::__set_user_id(const int16_t val) {
  this->user_id = val;
}

void MetaRequest::__set_file_name(const std::string& val) {
  this->file_name = val;
}

void MetaRequest::__set_offset(const int64_t val) {
  this->offset = val;
}

void MetaRequest::__set_length(const int64_t val) {
  this->length = val;
}
std::ostream& operator<<(std::ostream& out, const MetaRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t MetaRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_user_id = false;
  bool isset_file_name = false;
  bool isset_offset = false;
  bool isset_length = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->user_id);
          isset_user_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->file_name);
          isset_file_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->offset);
          isset_offset = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->length);
          isset_length = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_user_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_file_name)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_offset)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_length)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t MetaRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("MetaRequest");

  xfer += oprot->writeFieldBegin("user_id", ::apache::thrift::protocol::T_I16, 1);
  xfer += oprot->writeI16(this->user_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("file_name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->file_name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("offset", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->offset);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("length", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->length);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(MetaRequest &a, MetaRequest &b) {
  using ::std::swap;
  swap(a.user_id, b.user_id);
  swap(a.file_name, b.file_name);
  swap(a.offset, b.offset);
  swap(a.length, b.length);
}

MetaRequest::MetaRequest(const MetaRequest& other11) {
  user_id = other11.user_id;
  file_name = other11.file_name;
  offset = other11.offset;
  length = other11.length;
}
MetaRequest& MetaRequest::operator=(const MetaRequest& other12) {
  user_id = other12.user_id;
  file_name = other12.file_name;
  offset = other12.offset;
  length = other12.length;
  return *this;
}
void MetaRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "MetaRequest(";
  out << "user_id=" << to_string(user_id);
  out << ", " << "file_name=" << to_string(file_name);
  out << ", " << "offset=" << to_string(offset);
  out << ", " << "length=" << to_string(length);
  out << ")";
}


Response::~Response() noexcept {
}


void Response::__set_code(const ResponseCode::type val) {
  this->code = val;
}

void Response::__set_data(const std::vector<int8_t> & val) {
  this->data = val;
}
std::ostream& operator<<(std::ostream& out, const Response& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t Response::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_code = false;
  bool isset_data = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast13;
          xfer += iprot->readI32(ecast13);
          this->code = (ResponseCode::type)ecast13;
          isset_code = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->data.clear();
            uint32_t _size14;
            ::apache::thrift::protocol::TType _etype17;
            xfer += iprot->readListBegin(_etype17, _size14);
            this->data.resize(_size14);
            uint32_t _i18;
            for (_i18 = 0; _i18 < _size14; ++_i18)
            {
              xfer += iprot->readByte(this->data[_i18]);
            }
            xfer += iprot->readListEnd();
          }
          isset_data = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_code)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_data)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t Response::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Response");

  xfer += oprot->writeFieldBegin("code", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32((int32_t)this->code);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("data", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_BYTE, static_cast<uint32_t>(this->data.size()));
    std::vector<int8_t> ::const_iterator _iter19;
    for (_iter19 = this->data.begin(); _iter19 != this->data.end(); ++_iter19)
    {
      xfer += oprot->writeByte((*_iter19));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Response &a, Response &b) {
  using ::std::swap;
  swap(a.code, b.code);
  swap(a.data, b.data);
}

Response::Response(const Response& other20) {
  code = other20.code;
  data = other20.data;
}
Response& Response::operator=(const Response& other21) {
  code = other21.code;
  data = other21.data;
  return *this;
}
void Response::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Response(";
  out << "code=" << to_string(code);
  out << ", " << "data=" << to_string(data);
  out << ")";
}


MetaResponse::~MetaResponse() noexcept {
}


void MetaResponse::__set_info_list(const std::vector<ChunkInfo> & val) {
  this->info_list = val;
}

void MetaResponse::__set_code(const ResponseCode::type val) {
  this->code = val;
}
std::ostream& operator<<(std::ostream& out, const MetaResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t MetaResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_info_list = false;
  bool isset_code = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->info_list.clear();
            uint32_t _size22;
            ::apache::thrift::protocol::TType _etype25;
            xfer += iprot->readListBegin(_etype25, _size22);
            this->info_list.resize(_size22);
            uint32_t _i26;
            for (_i26 = 0; _i26 < _size22; ++_i26)
            {
              xfer += this->info_list[_i26].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_info_list = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast27;
          xfer += iprot->readI32(ecast27);
          this->code = (ResponseCode::type)ecast27;
          isset_code = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_info_list)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_code)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t MetaResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("MetaResponse");

  xfer += oprot->writeFieldBegin("info_list", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->info_list.size()));
    std::vector<ChunkInfo> ::const_iterator _iter28;
    for (_iter28 = this->info_list.begin(); _iter28 != this->info_list.end(); ++_iter28)
    {
      xfer += (*_iter28).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("code", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32((int32_t)this->code);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(MetaResponse &a, MetaResponse &b) {
  using ::std::swap;
  swap(a.info_list, b.info_list);
  swap(a.code, b.code);
}

MetaResponse::MetaResponse(const MetaResponse& other29) {
  info_list = other29.info_list;
  code = other29.code;
}
MetaResponse& MetaResponse::operator=(const MetaResponse& other30) {
  info_list = other30.info_list;
  code = other30.code;
  return *this;
}
void MetaResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "MetaResponse(";
  out << "info_list=" << to_string(info_list);
  out << ", " << "code=" << to_string(code);
  out << ")";
}

} // namespace
